# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.TextField(default='unavailable', null=True)),
                ('name', models.TextField(default='unavailable', null=True)),
                ('sex', models.TextField(default='unavailable', null=True)),
                ('age', models.TextField(default='unavailable', null=True)),
                ('contact_email', models.TextField(default='unavailable', null=True)),
                ('contact_phone', models.TextField(default='unavailable', null=True)),
                ('city', models.TextField(default='unavailable', null=True)),
                ('zip_code', models.TextField(default='unavailable', null=True)),
                ('size', models.TextField(default='unavailable', null=True)),
                ('description', models.TextField(default='unavailable', null=True)),
                ('adoptable', models.NullBooleanField(default=None)),
                ('fosterable', models.NullBooleanField(default=None)),
                ('profile_photo_url', models.CharField(default='', max_length=200, null=True)),
                ('breeds', models.ManyToManyField(to='app.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('dog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('dog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('favorites', models.ManyToManyField(default=None, to='app.Dog')),
            ],
        ),
    ]
