# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='fifth_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='fourth_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='second_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='sixth_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='third_photo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
